// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

/**
 * The format of the output, in one of these options: `json`, `text`, `srt`, `verbose_json`, or `vtt`.
 */
public enum AudioResponseFormat {
    /**
     * Enum value json.
     */
    JSON("json"),

    /**
     * Enum value text.
     */
    TEXT("text"),

    /**
     * Enum value srt.
     */
    SRT("srt"),

    /**
     * Enum value verbose_json.
     */
    VERBOSE_JSON("verbose_json"),

    /**
     * Enum value vtt.
     */
    VTT("vtt");

    /**
     * The actual serialized value for a AudioResponseFormat instance.
     */
    private final String value;

    AudioResponseFormat(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a AudioResponseFormat instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed AudioResponseFormat object, or null if unable to parse.
     */
    public static AudioResponseFormat fromString(String value) {
        if (value == null) {
            return null;
        }
        AudioResponseFormat[] items = AudioResponseFormat.values();
        for (AudioResponseFormat item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
