// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The ChatCompletionStreamResponseDeltaFunctionCall model.
 */
@Immutable
public final class ChatCompletionStreamResponseDeltaFunctionCall
    implements JsonSerializable<ChatCompletionStreamResponseDeltaFunctionCall> {
    /*
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not
     * always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the
     * arguments in your code before calling your function.
     */
    @Generated
    private String arguments;

    /*
     * The name of the function to call.
     */
    @Generated
    private String name;

    /**
     * Creates an instance of ChatCompletionStreamResponseDeltaFunctionCall class.
     */
    @Generated
    private ChatCompletionStreamResponseDeltaFunctionCall() {
    }

    /**
     * Get the arguments property: The arguments to call the function with, as generated by the model in JSON format.
     * Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your
     * function schema. Validate the arguments in your code before calling your function.
     * 
     * @return the arguments value.
     */
    @Generated
    public String getArguments() {
        return this.arguments;
    }

    /**
     * Get the name property: The name of the function to call.
     * 
     * @return the name value.
     */
    @Generated
    public String getName() {
        return this.name;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("arguments", this.arguments);
        jsonWriter.writeStringField("name", this.name);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of ChatCompletionStreamResponseDeltaFunctionCall from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of ChatCompletionStreamResponseDeltaFunctionCall if the JsonReader was pointing to an
     * instance of it, or null if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the ChatCompletionStreamResponseDeltaFunctionCall.
     */
    @Generated
    public static ChatCompletionStreamResponseDeltaFunctionCall fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            ChatCompletionStreamResponseDeltaFunctionCall deserializedChatCompletionStreamResponseDeltaFunctionCall
                = new ChatCompletionStreamResponseDeltaFunctionCall();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("arguments".equals(fieldName)) {
                    deserializedChatCompletionStreamResponseDeltaFunctionCall.arguments = reader.getString();
                } else if ("name".equals(fieldName)) {
                    deserializedChatCompletionStreamResponseDeltaFunctionCall.name = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedChatCompletionStreamResponseDeltaFunctionCall;
        });
    }
}
