// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

/**
 * Defines values for CreateTranscriptionRequestResponseFormat9.
 */
public enum CreateTranscriptionRequestResponseFormat9 {
    /**
     * Enum value text.
     */
    TEXT("text");

    /**
     * The actual serialized value for a CreateTranscriptionRequestResponseFormat9 instance.
     */
    private final String value;

    CreateTranscriptionRequestResponseFormat9(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a CreateTranscriptionRequestResponseFormat9 instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed CreateTranscriptionRequestResponseFormat9 object, or null if unable to parse.
     */
    public static CreateTranscriptionRequestResponseFormat9 fromString(String value) {
        if (value == null) {
            return null;
        }
        CreateTranscriptionRequestResponseFormat9[] items = CreateTranscriptionRequestResponseFormat9.values();
        for (CreateTranscriptionRequestResponseFormat9 item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
