// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

/**
 * Defines values for CreateModerationResponseResultCategoryAppliedInputTypesViolence.
 */
public enum CreateModerationResponseResultCategoryAppliedInputTypesViolence {
    /**
     * Enum value text.
     */
    TEXT("text"),

    /**
     * Enum value image.
     */
    IMAGE("image");

    /**
     * The actual serialized value for a CreateModerationResponseResultCategoryAppliedInputTypesViolence instance.
     */
    private final String value;

    CreateModerationResponseResultCategoryAppliedInputTypesViolence(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a CreateModerationResponseResultCategoryAppliedInputTypesViolence instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed CreateModerationResponseResultCategoryAppliedInputTypesViolence object, or null if unable to
     * parse.
     */
    public static CreateModerationResponseResultCategoryAppliedInputTypesViolence fromString(String value) {
        if (value == null) {
            return null;
        }
        CreateModerationResponseResultCategoryAppliedInputTypesViolence[] items
            = CreateModerationResponseResultCategoryAppliedInputTypesViolence.values();
        for (CreateModerationResponseResultCategoryAppliedInputTypesViolence item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
