// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The CreateChatCompletionResponseChoiceLogprobs model.
 */
@Immutable
public final class CreateChatCompletionResponseChoiceLogprobs
    implements JsonSerializable<CreateChatCompletionResponseChoiceLogprobs> {
    /*
     * A list of message content tokens with log probability information.
     */
    @Generated
    private final List<ChatCompletionTokenLogprob> content;

    /*
     * A list of message refusal tokens with log probability information.
     */
    @Generated
    private final List<ChatCompletionTokenLogprob> refusal;

    /**
     * Creates an instance of CreateChatCompletionResponseChoiceLogprobs class.
     * 
     * @param content the content value to set.
     * @param refusal the refusal value to set.
     */
    @Generated
    private CreateChatCompletionResponseChoiceLogprobs(List<ChatCompletionTokenLogprob> content,
        List<ChatCompletionTokenLogprob> refusal) {
        this.content = content;
        this.refusal = refusal;
    }

    /**
     * Get the content property: A list of message content tokens with log probability information.
     * 
     * @return the content value.
     */
    @Generated
    public List<ChatCompletionTokenLogprob> getContent() {
        return this.content;
    }

    /**
     * Get the refusal property: A list of message refusal tokens with log probability information.
     * 
     * @return the refusal value.
     */
    @Generated
    public List<ChatCompletionTokenLogprob> getRefusal() {
        return this.refusal;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("content", this.content, (writer, element) -> writer.writeJson(element));
        jsonWriter.writeArrayField("refusal", this.refusal, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of CreateChatCompletionResponseChoiceLogprobs from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of CreateChatCompletionResponseChoiceLogprobs if the JsonReader was pointing to an instance
     * of it, or null if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the CreateChatCompletionResponseChoiceLogprobs.
     */
    @Generated
    public static CreateChatCompletionResponseChoiceLogprobs fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            List<ChatCompletionTokenLogprob> content = null;
            List<ChatCompletionTokenLogprob> refusal = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("content".equals(fieldName)) {
                    content = reader.readArray(reader1 -> ChatCompletionTokenLogprob.fromJson(reader1));
                } else if ("refusal".equals(fieldName)) {
                    refusal = reader.readArray(reader1 -> ChatCompletionTokenLogprob.fromJson(reader1));
                } else {
                    reader.skipChildren();
                }
            }
            return new CreateChatCompletionResponseChoiceLogprobs(content, refusal);
        });
    }
}
