// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

/**
 * Defines values for CreateTranscriptionRequestTimestampGranularity.
 */
public enum CreateTranscriptionRequestTimestampGranularity {
    /**
     * Enum value word.
     */
    WORD("word"),

    /**
     * Enum value segment.
     */
    SEGMENT("segment");

    /**
     * The actual serialized value for a CreateTranscriptionRequestTimestampGranularity instance.
     */
    private final String value;

    CreateTranscriptionRequestTimestampGranularity(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a CreateTranscriptionRequestTimestampGranularity instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed CreateTranscriptionRequestTimestampGranularity object, or null if unable to parse.
     */
    public static CreateTranscriptionRequestTimestampGranularity fromString(String value) {
        if (value == null) {
            return null;
        }
        CreateTranscriptionRequestTimestampGranularity[] items
            = CreateTranscriptionRequestTimestampGranularity.values();
        for (CreateTranscriptionRequestTimestampGranularity item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
