// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

/**
 * Defines values for CreateModerationResponseResultCategoryAppliedInputTypesSelfHarmIntent.
 */
public enum CreateModerationResponseResultCategoryAppliedInputTypesSelfHarmIntent {
    /**
     * Enum value text.
     */
    TEXT("text"),

    /**
     * Enum value image.
     */
    IMAGE("image");

    /**
     * The actual serialized value for a CreateModerationResponseResultCategoryAppliedInputTypesSelfHarmIntent instance.
     */
    private final String value;

    CreateModerationResponseResultCategoryAppliedInputTypesSelfHarmIntent(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a CreateModerationResponseResultCategoryAppliedInputTypesSelfHarmIntent instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed CreateModerationResponseResultCategoryAppliedInputTypesSelfHarmIntent object, or null if
     * unable to parse.
     */
    public static CreateModerationResponseResultCategoryAppliedInputTypesSelfHarmIntent fromString(String value) {
        if (value == null) {
            return null;
        }
        CreateModerationResponseResultCategoryAppliedInputTypesSelfHarmIntent[] items
            = CreateModerationResponseResultCategoryAppliedInputTypesSelfHarmIntent.values();
        for (CreateModerationResponseResultCategoryAppliedInputTypesSelfHarmIntent item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
