// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

/**
 * Defines values for CreateModerationResponseResultCategoryAppliedInputTypesViolenceGraphic.
 */
public enum CreateModerationResponseResultCategoryAppliedInputTypesViolenceGraphic {
    /**
     * Enum value text.
     */
    TEXT("text"),

    /**
     * Enum value image.
     */
    IMAGE("image");

    /**
     * The actual serialized value for a CreateModerationResponseResultCategoryAppliedInputTypesViolenceGraphic
     * instance.
     */
    private final String value;

    CreateModerationResponseResultCategoryAppliedInputTypesViolenceGraphic(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a CreateModerationResponseResultCategoryAppliedInputTypesViolenceGraphic instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed CreateModerationResponseResultCategoryAppliedInputTypesViolenceGraphic object, or null if
     * unable to parse.
     */
    public static CreateModerationResponseResultCategoryAppliedInputTypesViolenceGraphic fromString(String value) {
        if (value == null) {
            return null;
        }
        CreateModerationResponseResultCategoryAppliedInputTypesViolenceGraphic[] items
            = CreateModerationResponseResultCategoryAppliedInputTypesViolenceGraphic.values();
        for (CreateModerationResponseResultCategoryAppliedInputTypesViolenceGraphic item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
