// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The RunObjectRequiredActionSubmitToolOutputs model.
 */
@Immutable
public final class RunObjectRequiredActionSubmitToolOutputs
    implements JsonSerializable<RunObjectRequiredActionSubmitToolOutputs> {
    /*
     * A list of the relevant tool calls.
     */
    @Generated
    private final List<RunToolCallObject> toolCalls;

    /**
     * Creates an instance of RunObjectRequiredActionSubmitToolOutputs class.
     * 
     * @param toolCalls the toolCalls value to set.
     */
    @Generated
    private RunObjectRequiredActionSubmitToolOutputs(List<RunToolCallObject> toolCalls) {
        this.toolCalls = toolCalls;
    }

    /**
     * Get the toolCalls property: A list of the relevant tool calls.
     * 
     * @return the toolCalls value.
     */
    @Generated
    public List<RunToolCallObject> getToolCalls() {
        return this.toolCalls;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeArrayField("tool_calls", this.toolCalls, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RunObjectRequiredActionSubmitToolOutputs from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of RunObjectRequiredActionSubmitToolOutputs if the JsonReader was pointing to an instance of
     * it, or null if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the RunObjectRequiredActionSubmitToolOutputs.
     */
    @Generated
    public static RunObjectRequiredActionSubmitToolOutputs fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            List<RunToolCallObject> toolCalls = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("tool_calls".equals(fieldName)) {
                    toolCalls = reader.readArray(reader1 -> RunToolCallObject.fromJson(reader1));
                } else {
                    reader.skipChildren();
                }
            }
            return new RunObjectRequiredActionSubmitToolOutputs(toolCalls);
        });
    }
}
