// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azureopenai;

import com.azure.core.util.ServiceVersion;

/**
 * Service version of AzureOpenAIClient.
 */
public enum AzureOpenAIServiceVersion implements ServiceVersion {
    /**
     * Enum value 2024-04-01-preview.
     */
    V2024_04_01_PREVIEW("2024-04-01-preview"),

    /**
     * Enum value 2024-05-01-preview.
     */
    V2024_05_01_PREVIEW("2024-05-01-preview"),

    /**
     * Enum value 2024-06-01.
     */
    V2024_06_01("2024-06-01"),

    /**
     * Enum value 2024-07-01-preview.
     */
    V2024_07_01_PREVIEW("2024-07-01-preview"),

    /**
     * Enum value 2024-08-01-preview.
     */
    V2024_08_01_PREVIEW("2024-08-01-preview");

    private final String version;

    AzureOpenAIServiceVersion(String version) {
        this.version = version;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getVersion() {
        return this.version;
    }

    /**
     * Gets the latest service version supported by this client library.
     * 
     * @return The latest {@link AzureOpenAIServiceVersion}.
     */
    public static AzureOpenAIServiceVersion getLatest() {
        return V2024_08_01_PREVIEW;
    }
}
