// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;
import com.openai.implementation.AudiosImpl;
import com.openai.implementation.MultipartFormDataHelper;
import com.openai.models.CreateSpeechRequest;
import com.openai.models.CreateTranscriptionRequest;
import com.openai.models.CreateTranscriptionResponseVerboseJson;
import com.openai.models.CreateTranslationRequest;
import com.openai.models.CreateTranslationResponseVerboseJson;
import java.util.Objects;

/**
 * Initializes a new instance of the synchronous OpenAIClient type.
 */
@ServiceClient(builder = OpenAIClientBuilder.class)
public final class AudioClient {
    @Generated
    private final AudiosImpl serviceClient;

    /**
     * Initializes an instance of AudioClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Generated
    AudioClient(AudiosImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Generates audio from the input text.
     * <p><strong>Request Body Schema</strong></p>
     * 
     * <pre>{@code
     * {
     *     model: String(tts-1/tts-1-hd) (Required)
     *     input: String (Required)
     *     voice: String(alloy/echo/fable/onyx/nova/shimmer) (Required)
     *     response_format: String(mp3/opus/aac/flac/wav/pcm) (Optional)
     *     speed: Double (Optional)
     * }
     * }</pre>
     * 
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>{@code
     * BinaryData
     * }</pre>
     * 
     * @param requestBody The requestBody parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createSpeechWithResponse(BinaryData requestBody, RequestOptions requestOptions) {
        return this.serviceClient.createSpeechWithResponse(requestBody, requestOptions);
    }

    /**
     * Transcribes audio into the input language.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>{@code
     * {
     *     task: String (Required)
     *     language: String (Required)
     *     duration: double (Required)
     *     text: String (Required)
     *     words (Optional): [
     *          (Optional){
     *             word: String (Required)
     *             start: double (Required)
     *             end: double (Required)
     *         }
     *     ]
     *     segments (Optional): [
     *          (Optional){
     *             id: int (Required)
     *             seek: int (Required)
     *             start: double (Required)
     *             end: double (Required)
     *             text: String (Required)
     *             tokens (Required): [
     *                 int (Required)
     *             ]
     *             temperature: double (Required)
     *             avg_logprob: double (Required)
     *             compression_ratio: double (Required)
     *             no_speech_prob: double (Required)
     *         }
     *     ]
     * }
     * }</pre>
     * 
     * @param requestBody The requestBody parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return represents a verbose json transcription response returned by model, based on the provided input along
     * with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    Response<BinaryData> createTranscriptionWithResponse(BinaryData requestBody, RequestOptions requestOptions) {
        // Protocol API requires serialization of parts with content-disposition and data, as operation
        // 'createTranscription' is 'multipart/form-data'
        return this.serviceClient.createTranscriptionWithResponse(requestBody, requestOptions);
    }

    /**
     * Translates audio into English..
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>{@code
     * {
     *     task: String (Required)
     *     language: String (Required)
     *     duration: double (Required)
     *     text: String (Required)
     *     segments (Optional): [
     *          (Optional){
     *             id: int (Required)
     *             seek: int (Required)
     *             start: double (Required)
     *             end: double (Required)
     *             text: String (Required)
     *             tokens (Required): [
     *                 int (Required)
     *             ]
     *             temperature: double (Required)
     *             avg_logprob: double (Required)
     *             compression_ratio: double (Required)
     *             no_speech_prob: double (Required)
     *         }
     *     ]
     * }
     * }</pre>
     * 
     * @param requestBody The requestBody parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    Response<BinaryData> createTranslationWithResponse(BinaryData requestBody, RequestOptions requestOptions) {
        // Protocol API requires serialization of parts with content-disposition and data, as operation
        // 'createTranslation' is 'multipart/form-data'
        return this.serviceClient.createTranslationWithResponse(requestBody, requestOptions);
    }

    /**
     * Generates audio from the input text.
     * 
     * @param requestBody The requestBody parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public BinaryData createSpeech(CreateSpeechRequest requestBody) {
        // Generated convenience method for createSpeechWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createSpeechWithResponse(BinaryData.fromObject(requestBody), requestOptions).getValue();
    }

    /**
     * Transcribes audio into the input language.
     * 
     * @param requestBody The requestBody parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return represents a verbose json transcription response returned by model, based on the provided input.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public CreateTranscriptionResponseVerboseJson createTranscription(CreateTranscriptionRequest requestBody) {
        // Generated convenience method for createTranscriptionWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createTranscriptionWithResponse(new MultipartFormDataHelper(requestOptions)
            .serializeFileField("file", requestBody.getFile().getContent(), requestBody.getFile().getContentType(),
                requestBody.getFile().getFilename())
            .serializeTextField("model", Objects.toString(requestBody.getModel()))
            .serializeTextField("language", requestBody.getLanguage())
            .serializeTextField("prompt", requestBody.getPrompt())
            .serializeTextField("response_format", Objects.toString(requestBody.getResponseFormat()))
            .serializeTextField("temperature", Objects.toString(requestBody.getTemperature()))
            .serializeJsonField("timestamp_granularities", requestBody.getTimestampGranularities())
            .end()
            .getRequestBody(), requestOptions).getValue().toObject(CreateTranscriptionResponseVerboseJson.class);
    }

    /**
     * Translates audio into English..
     * 
     * @param requestBody The requestBody parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public CreateTranslationResponseVerboseJson createTranslation(CreateTranslationRequest requestBody) {
        // Generated convenience method for createTranslationWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createTranslationWithResponse(new MultipartFormDataHelper(requestOptions)
            .serializeFileField("file", requestBody.getFile().getContent(), requestBody.getFile().getContentType(),
                requestBody.getFile().getFilename())
            .serializeTextField("model", Objects.toString(requestBody.getModel()))
            .serializeTextField("prompt", requestBody.getPrompt())
            .serializeTextField("response_format", Objects.toString(requestBody.getResponseFormat()))
            .serializeTextField("temperature", Objects.toString(requestBody.getTemperature()))
            .end()
            .getRequestBody(), requestOptions).getValue().toObject(CreateTranslationResponseVerboseJson.class);
    }
}
