// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * Package containing the data models for AzureOpenAI.
 */
package com.azure.ai.openai.implementation.models;
